language: python
python:
  - "3.5"

services:
  - docker

before_install:
- docker pull nipype/workshops:latest-complete
- docker run -d nipype/workshops:latest-complete

# command to run tests
#script: py.test tests_unit/test_temp.py